version: '3.9'

services:
  app: 
    build: 
      context: ..
      dockerfile: DOCKER/Dockerfile

    container_name: MediTriage
    ports:
      - "3000:3000"
    environment:
      - OCR_SPACE_API_KEY=
      - GEMINI_API_KEY=
      - OCR_SPACE_LANGUAGE=eng
      - OCR_SPACE_OCR_ENGINE=3
      # this is free api link for oci space
      - OCR_SPACE_API=https://api.ocr.space/parse/image 
      - GEMINI_MODEL=gemini-3.1-flash-lite
      - MONGODB_URI=mongodb://mongo:27017/patient
    depends_on:
      - mongo

  mongo:
    image: mongo:8.3.4
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
